dengste/org-caldav

org-caldav.el
If case-fold-search is t, the matching done to chop off possible
prefixes added by org-mode (i.e. the [A-Z][A-Z][0-9]*-) regexp, may
match a legitimate UID that just happens to have the first chunk
be two characters and followed by only numbers. This results in the
first chunk of the UID being chopped off, breaking UID matching.
This makes sure case-fold-search is set to nil in org-caldav-get-uid.
Signed-off-by: Toke Høiland-Jørgensen <toke@toke.dk>
=> Make sure matching is case-sensitive in org-caldav-get-uid.

org-caldav-testsuite.el, org-caldav.el
This commit allows nil to be passed as the UID parameter to
`org-caldav-insert-org-entry`. This is useful when automatically filling
`org-caldav-inbox` with entries generated from .ics files (e.g., from
emails).
This commit also introduces a unit test for this method.
=> org-caldav-insert-org-entry now allows null UID

org-caldav.el
Many calendar apps will not show an .ics event unless it contains such a line.
=> Add an empty "PRODID:" entry to the calendar preamble.

org-caldav.el
Without this, UIDs have the first part stripped if they happen to start with two letters [A-F], followed by numbers, resulting in an error.
Probably fixes #58.
=> Fix regexp in org-caldav-get-uid.

org-caldav.el
When synchronizing several calendars, I find it annoying that `org-caldav-sync` stopped for every missing files.
This patch prompt for the user's permission to create the missing files.
=> Ask if the user wants to create the missing inbox files

org-caldav.el
This is an initial attempt at a fix for #137.
Matching against org-tr-regexp first allows correctly replacing the whole time range in cases where the start date of a range has been updated on the server.
=> org-caldav-change-timestamp: also match against time ranges

org-caldav.el
...rather than `put-text-property`; change `org-caldav-goto-uid` to
non-interactive; remove (now redundant) bindings for `org-caldav-goto-uid`, and
add bindings for `forward-button` and `backward-button`.
This allows the user to use `forward-button` and `backward-button` to navigate
between UID links in the results buffer.
=> Change `org-caldav-sync-result-print-entries' to use `make-button'

org-caldav.el
The function `org-caldav-create-time-range` can be called from `org-caldav-update-events-in-org` with an incorrect number of arguments. The original code passes `(butlast eventdata 3)` as arguments. However, since `org-caldav-create-time-range` expects exactly four arguments, this will fail unless `eventdata` has exactly seven elements.
The fix replaces `(butlast eventdata 3)` with `(seq-take eventdata 4)`.
I managed to trigger the failure once when I added a "note" to a Google calendar event ("DESCRIPTION:" in caldav).
Edit: On second thoughts, this bug might only be necessary if you have have added CLASS (pull request #161). Adding the fix to the main branch would still remove the latent bug.
=> Bugfix for org-caldav-create-time-range: Incorrect number of args

org-caldav.el
Proposed (partial?) fix for issue #139
Supersedes PR #140 (use knatsakis/org-caldav branch org-caldav-empty-calendar as head fork instead of master)
=> Reset org-caldav-empty-calendar before syncing

org-caldav.el
Please consider merging this.
With this patch, UIDs will not be added to org entries that match org-caldav-skip-conditions and will not be synced anyway.
So, by using a skip condition (e.g.: 'nottimestamp), one can avoid _polluting_ the org file with useless UIDs (UIDs will be added only to entries with a timestamp).
=> Do not add UIDs to entries that match org-caldav-skip-conditions

org-caldav.el
Fix a minor error introduced in my pull request #172.
Great to see you maintaining this package again!
=> fix binding of backtab: `backward-button' instead of `forward-button'

org-caldav.el
I noticed this while looking at some syncing issue.  This may look nicer.
=> Use `format` for all debug messages

org-caldav.el
`org-set-tags' assumes that the cursor is already on a headline. I have been getting results like:
*** Example Event
:PROPERTIES:
:ID:       1237293742980p20138-298
:END:
<2019-12-22 Sun 06:30-18:30>  :export:
This commit ensures that the select tags are put on the headline.
=> Fix: tags being inserted in the entry body, not headline

org-caldav.el
I often find myself looking into the source to check if the change I'm confirming will happen in my local copy of the calendar or in the external server. To avoid this I propose the following message changes.
=> Clarified confirmation messages

org-caldav.el
I have followed a tip published on orgmode mailing list (https://www.mail-archive.com/emacs-orgmode@gnu.org/msg127148.html). Seems to fix the problem, although I haven't tested incredibly thoroughly.
=> Replace org-maybe-keyword-time-regexp (fix for Org 9.4)

org-caldav-testsuite.el, org-caldav.el
Most of the unit tests currently fail on recent versions of Emacs and Org. There are multiple bugs causing this, mainly related to timestamp and ID handling; some of the problems were caused by breaking changes in upstream Org mode since org-caldav was last updated.
This PR fixes the unit tests as well as underlying bugs. The commit messages contained within this PR have some more details about the specific bugs and when they were introduced.
Fixes #251, fixes #230
=> Fix timestamp & ID bugs to make the unit tests work again

README.md, org-caldav.el
----
Also clean up mixed tabs and indentation.
Original "days in past" commit author: Martin Kaffanke <m.kaffanke_at_gmail.com>
After/if this PR gets merged I've got some more changes I've collected from various forks (like vtodo support) cleaned up so they apply on top of this.
#
=> Add days-in-past to keep the remote calendar clean.

README.md, org-caldav.el
This PR brings in some commits from @grauschnabel's fork  I've adapted to your `master` plus some fixes on top of it.
Edit: Original PR from the author of most of the work here: #118
=> Add support for syncing TODOs

org-caldav.el
with a large number of calendar-files, the unfixed code will create malformed lisp forms containing `...`  in the `.org-caldav-sync/org-caldav-hash.el` files:
```
(setq org-caldav-previous-files '("my-file.org" ...))
```
leading to this:
```
Debugger entered--Lisp error: (wrong-type-argument sequencep \...)
mapconcat(identity (\...) ",")
#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>()
funcall(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>)
(let ((org-caldav-calendar-id '"personal") (org-caldav-files '(foo bar baz ...))) (funcall '#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>))
eval((let ((org-caldav-calendar-id '"personal") (org-caldav-files '(foo bar baz ...)))) (funcall '#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_26>))) …
```
=> fix: never emit shortening ellipsis in "(setq org-caldav-previous-files ...)"

org-caldav.el
`parse-time-string` fails on some repeating events. For example: 
```elisp
(parse-time-string "<2023-10-09 Mon +100d>")
```
Gives back the error
```
cl-parse-integer: Not an integer string: ‘+100d’
```
=> Fix cl-parse-integer: Not an integer string

org-caldav.el
This PR is to update org-caldav to use lexical binding as recommended in the Emacs coding conventions:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html
I'm going to test-drive this a little bit before merging in case any issues arise.
Feedback is appreciated if anyone else wants to test this out.
As an aside, I found this comment thread on org-agenda's migration to lexical binding to be informative:
https://list.orgmode.org/87a6rsg0vb.fsf@kyleam.com/t/
=> Convert to lexical binding

doc/org-caldav.org, org-caldav-tests.el, org-caldav.el
Fixes #150 
This seems to be working, but I plan to add some unit tests before merging.
Also should update the documentation to note this is supported now, but only for simple cases (no iCal UNTIL or COUNT properties), and also to note some subtleties in the case of TODOs (e.g. the user may want to set `org-icalendar-todo-unscheduled-start`).
I'm opening the PR now for visibility and so people can test it out if they like.
=> Implement recurring events and todos

org-caldav.el
These 2 functions can be used by the user as is.
=> Make 2 ICS-importing functions interactive
